App\Entity\Location:
  properties:
    latitude:
      - Range:
          groups: [new, edit]
          min: -90
          max: 90
          notInRangeMessage: You must be between {{ min }} and {{ max }}
    longitude:
      - Range:
          groups: [new, edit]
          min: -180
          max: 180
          notInRangeMessage: You must be between {{ min }} and {{ max }}
