#index:
#    path: /
#    controller: App\Controller\DefaultController::index

weather_at_location:
  path: /weather/{location}
  controller: App\Controller\WeatherController::locationWeather
  requirements:
    location: \d+

weather_by_country_and_city:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController::weatherByCountryAndCity

app_logout:
  path: /logout
  methods: GET

admin_index:
  path: /admin
  controller: App\Controller\AdminController:index
